# Generated by Django 3.0.8 on 2020-07-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance_officer',
            name='catering',
        ),
        migrations.RemoveField(
            model_name='finance_officer',
            name='dean_of_students',
        ),
        migrations.RemoveField(
            model_name='finance_officer',
            name='games',
        ),
        migrations.RemoveField(
            model_name='finance_officer',
            name='hostels',
        ),
        migrations.RemoveField(
            model_name='finance_officer',
            name='labs_and_workshops',
        ),
        migrations.RemoveField(
            model_name='finance_officer',
            name='library',
        ),
        migrations.RemoveField(
            model_name='finance_officer',
            name='registrar_of_academics',
        ),
        migrations.RemoveField(
            model_name='finance_officer',
            name='student_finance',
        ),
        migrations.DeleteModel(
            name='Catering',
        ),
        migrations.DeleteModel(
            name='Dean_of_Students',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.DeleteModel(
            name='Games_Department',
        ),
        migrations.DeleteModel(
            name='Hostels',
        ),
        migrations.DeleteModel(
            name='Labs_and_Workshops',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='Registrar_of_Academics',
        ),
    ]
