# Generated by Django 3.0.8 on 2020-07-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200707_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finance_Officer',
        ),
    ]
